# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Limes
                                 A QGIS plugin
 This plugin download and show Roman military installations alongside the frontiers of the Roman Empire (Limes)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-02-14
        copyright            : (C) 2022 by Václav FRÖHLICH / ENVIPARTNER, s.r.o. / Michal Dyčka
        email                : frohlich@envipartner.cz
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Limes class from file Limes.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Limes import Limes
    return Limes(iface)
